from time import sleep


def introAnimation():
    sleep(0.15)
    print("\n")
    sleep(0.15)
    print(      "        ")
    sleep(0.15)
    print(      "                 _.---,_")
    sleep(0.15)
    print(      "               .'       `'.")
    sleep(0.15)
    print(      "                \    __..-'\'")
    sleep(0.15)
    print(      "                 }-\"`       \'")
    sleep(0.15)
    print(      "                /__,,..---.._|")
    sleep(0.15)
    print(      "                \            |")
    sleep(0.15)
    print(      "                |---..__     |")
    sleep(0.15)
    print(      "               /        ``\"-./")
    sleep(0.15)
    print(      "             .'---...__      |")
    sleep(0.15)
    print(     "           .'          ``\"-./")
    sleep(0.15)
    print(  "      ,--./...,,,__        /")
    sleep(0.15)
    print( "      '--.'__    __```.-. /._")
    sleep(0.15)
    print( "        / `  `  '  `=/.-.|-._)")
    sleep(0.15)
    print( "        | .-.  .-.  \"\'\'  /")
    sleep(0.15)
    print( "        || O| | O|  \"\"=='_\'")
    sleep(0.15)
    print( "      .-' '-'o '-'    \"\"=\`")
    sleep(0.1)
    print( "`''--/-              \"\"=-,\--._")
    sleep(0.1)
    print( ".---|-            ( \"\"=-. \`")
    sleep(0.1)
    print( "    \             /`)\"=.\"=|'-.")
    sleep(0.1)
    print( "     '.       _.-' '  \"=|\|")
    sleep(0.1)
    print( "       (`----`    '=\"=|/")
    sleep(0.1)
    print( "        `-.       \"=/`")
    sleep(0.1)
    print( "           '.     =/")
    sleep(0.1)
    print( "             \   =|")
    sleep(0.1)
    print( "  .-.        |` \"=|")
    sleep(0.1)
    print( " (   ~._     | \"==|        _.-~`\'")
    sleep(0.1)
    print( "  \     ~.   |'\"=\"|    _.-~      )")
    sleep(0.1)
    print( "   ;      ~-.|.-._|_.-~         /")
    sleep(0.1)
    print( "  /        _-(  /-.__          (")
    sleep(0.1)
    print( " '._..--~~`/`/-'\-._ `~~-       ;")
    sleep(0.1)
    print( "          /\"=|  |\" =\~-...___.-~")
    sleep(0.1)
    print( "         /=\" /  | \"==\'")
    sleep(0.1)
    print( "        / = (_  \  \"==\'")
    sleep(0.1)
    print(      "       ;=\"=   `\_)  ==\"\'")
    sleep(0.1)
    print(      "    ")
